### ISSUE TITLE
String.arbitrary.generate Crashes when compiled as `Release`

### ISSUE THREAD

**Issue by kykim** [typelift/SwiftCheck#137] opened 2015-12-26 05:39 UTC
v0.4.2
Notice this because I install via `Carthage`.

Property.swift:476
```
@effects(readnone)
internal func • <A, B, C>(f : B -> C, g : A -> B) -> A -> C {
	return { f(g($0)) }
}
```

Backtrace is here: https://gist.github.com/kykim/eafe1ec7b5c040fe5a1b

Simple fix is to pass `--configuration Debug` to `Carthage`, but this seems a bit odd.

**Comment by CodaFi** [comment] 2015-12-26 16:23
Did you manage to get the seed numbers for each and a specific test?  We can reproduce with those.

**Comment by kykim** [comment] 2015-12-27 02:48
how do i grab the seed numbers?

**Comment by CodaFi** [comment] 2015-12-27 02:52
Actually, it looks like you called `generate` in your test for some reason.  In that case if you can show the test case I should be able to reproduce it.  If you need to strip anything out, please leave the SwiftCheck calls intact with dummy values in place of your private code.

**Comment by kykim** [comment] 2015-12-28 18:30
I created a PR with the test case here: https://github.com/typelift/SwiftCheck/pull/138
Basically, I'm creating an `ArbitraryNSData` struct that uses `String.arbitrary.generate` underneath.
As I stated before, this passes with the `DEBUG` Build Configuration, but crashes with `RELEASE`.

HTH and Thanks!
-kevin

**Comment by CodaFi** [comment] 2015-12-28 22:20
Fixed by the merger of #136.  I'm going to put out a new minor release to patch this and you should be all set to go!

If you have any more questions or come across any more issues, don't hesitate to open more issues.
:sparkles:

**Closed by CodaFi** 2015-12-28 22:20 UTC

**Comment by kykim** [comment] 2015-12-29 05:19
awesome!
what was the cause and fix? did it just get "fixed" with the changes you had queued up?

thanks again!

**Comment by CodaFi** [comment] 2015-12-29 07:22
I can't be sure of the exact cause because it has to do with the optimizer, but I had committed a bunch of @effects annotations all over this code base.  Erroneously, quite a few functions were violating their contracts, so I removed them.  It had the added benefit of speeding up compile times so I just rolled everything up into the pull request where I was trying to do that already 

et viola
